name: Docker Hub Token Access

on:
  workflow_dispatch:

jobs:
  get-dockerhub-token:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (opcional)
        uses: actions/checkout@v4

      - name: Run Docker Hub token fetcher
        uses: docker://alpine:latest
        env:
          DOCKERHUB_AUTH: ${{ secrets.DOCKERHUB_AUTH }}
        run: |
          apk add --no-cache curl jq
          
          USERNAME=$(echo "$DOCKERHUB_AUTH" | cut -d ':' -f1)
          PASSWORD=$(echo "$DOCKERHUB_AUTH" | cut -d ':' -f2)

          TOKEN=$(curl -s -X POST "https://hub.docker.com/v2/users/login/" \
            -H "Content-Type: application/json" \
            -d "{\"username\": \"${USERNAME}\", \"password\": \"${PASSWORD}\"}" | jq -r '.token')

          if [ "$TOKEN" = "null" ] || [ -z "$TOKEN" ]; then
            echo "❌ Error: No se pudo obtener el token de Docker Hub"
            exit 1
          fi

          echo "✅ Token obtenido correctamente. Consultando access tokens..."

          curl -s -X GET "https://hub.docker.com/v2/access-tokens?page=1&page_size=10" \
            -H "Authorization: Bearer $TOKEN" | jq .
