name: DockerHub Auth Test

on:
  workflow_dispatch:

jobs:
  test-dockerhub-token:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create DockerHub secret file
        run: echo "${{ secrets.DOCKERHUB_AUTH }}" > my_dockerhub_token.txt

      - name: Build image with DockerHub auth
        run: |
          DOCKER_BUILDKIT=1 docker build \
            --secret id=my_dockerhub_token,src=my_dockerhub_token.txt \
            -t dockerhub-auth-check .
