name: Build Docker with Secret

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create secret file
        run: |
          echo "${{ secrets.MY_SECRET }}" > my_secret.txt

      - name: Build Docker image with secret
        run: |
          DOCKER_BUILDKIT=1 docker build \
            --secret id=my_secret,src=my_secret.txt \
            -t test-image .

      - name: Show Docker history
        run: docker history test-image
